insert into congelateur (id, nom, description, utilisateur_id) values (1, 'quisque', 'parturient montes nascetur ridiculus mus vivamus vestibulum', 5);
insert into congelateur (id, nom, description, utilisateur_id) values (2, 'aliquam', 'interdum mauris ullamcorper purus sit amet nulla quisque', 1);
insert into congelateur (id, nom, description, utilisateur_id) values (3, 'pede', 'libero nullam sit amet turpis', 12);
insert into congelateur (id, nom, description, utilisateur_id) values (4, 'faucibus', 'sapien quis libero nullam sit amet turpis elementum', 11);
insert into congelateur (id, nom, description, utilisateur_id) values (5, 'nec', 'aliquam augue quam sollicitudin vitae consectetuer', 12);
insert into congelateur (id, nom, description, utilisateur_id) values (6, 'eu', 'sit amet consectetuer adipiscing elit proin risus', 7);
insert into congelateur (id, nom, description, utilisateur_id) values (7, 'vestibulum', 'pede malesuada in imperdiet et commodo vulputate', 10);
insert into congelateur (id, nom, description, utilisateur_id) values (8, 'sit', 'morbi quis tortor id nulla ultrices aliquet', 4);
insert into congelateur (id, nom, description, utilisateur_id) values (9, 'cubilia', 'risus praesent lectus vestibulum quam sapien', 5);
insert into congelateur (id, nom, description, utilisateur_id) values (10, 'sapien', 'gravida sem praesent id massa id nisl venenatis', 5);
insert into congelateur (id, nom, description, utilisateur_id) values (11, 'turpis', 'neque vestibulum eget vulputate ut ultrices', 15);
insert into congelateur (id, nom, description, utilisateur_id) values (12, 'quis', 'non velit donec diam neque vestibulum', 14);
insert into congelateur (id, nom, description, utilisateur_id) values (13, 'nulla', 'lacinia sapien quis libero nullam sit', 5);
insert into congelateur (id, nom, description, utilisateur_id) values (14, 'donec', 'ligula pellentesque ultrices phasellus id sapien in sapien', 4);
insert into congelateur (id, nom, description, utilisateur_id) values (15, 'augue', 'sollicitudin vitae consectetuer eget rutrum', 9);
insert into congelateur (id, nom, description, utilisateur_id) values (16, 'pulvinar', 'tempor convallis nulla neque libero convallis eget eleifend', 12);
insert into congelateur (id, nom, description, utilisateur_id) values (17, 'cursus', 'potenti in eleifend quam a', 11);
insert into congelateur (id, nom, description, utilisateur_id) values (18, 'posuere', 'integer tincidunt ante vel ipsum praesent', 11);
insert into congelateur (id, nom, description, utilisateur_id) values (19, 'consequat', 'nulla ultrices aliquet maecenas leo odio condimentum id', 15);
insert into congelateur (id, nom, description, utilisateur_id) values (20, 'dictumst', 'quis justo maecenas rhoncus aliquam lacus morbi quis', 3);
insert into congelateur (id, nom, description, utilisateur_id) values (21, 'eu', 'adipiscing elit proin interdum mauris non', 11);
insert into congelateur (id, nom, description, utilisateur_id) values (22, 'imperdiet', 'ut erat curabitur gravida nisi at nibh', 14);
insert into congelateur (id, nom, description, utilisateur_id) values (23, 'dapibus', 'nunc viverra dapibus nulla suscipit ligula in lacus', 6);
insert into congelateur (id, nom, description, utilisateur_id) values (24, 'iaculis', 'diam neque vestibulum eget vulputate ut ultrices', 14);
insert into congelateur (id, nom, description, utilisateur_id) values (25, 'varius', 'hac habitasse platea dictumst morbi', 11);
insert into congelateur (id, nom, description, utilisateur_id) values (26, 'dictumst', 'ipsum dolor sit amet consectetuer', 11);
insert into congelateur (id, nom, description, utilisateur_id) values (27, 'dapibus', 'augue luctus tincidunt nulla mollis molestie lorem', 8);
insert into congelateur (id, nom, description, utilisateur_id) values (28, 'mauris', 'justo etiam pretium iaculis justo in hac habitasse', 7);
insert into congelateur (id, nom, description, utilisateur_id) values (29, 'accumsan', 'donec semper sapien a libero', 5);
insert into congelateur (id, nom, description, utilisateur_id) values (30, 'et', 'consequat dui nec nisi volutpat', 13);
insert into congelateur (id, nom, description, utilisateur_id) values (31, 'adipiscing', 'non interdum in ante vestibulum ante', 6);
insert into congelateur (id, nom, description, utilisateur_id) values (32, 'metus', 'erat nulla tempus vivamus in felis eu sapien', 12);
insert into congelateur (id, nom, description, utilisateur_id) values (33, 'ac', 'ac lobortis vel dapibus at diam', 8);
insert into congelateur (id, nom, description, utilisateur_id) values (34, 'accumsan', 'turpis adipiscing lorem vitae mattis', 11);
insert into congelateur (id, nom, description, utilisateur_id) values (35, 'lectus', 'placerat praesent blandit nam nulla integer pede', 11);
insert into congelateur (id, nom, description, utilisateur_id) values (36, 'pulvinar', 'porttitor lorem id ligula suspendisse', 3);
insert into congelateur (id, nom, description, utilisateur_id) values (37, 'et', 'lorem id ligula suspendisse ornare', 14);
insert into congelateur (id, nom, description, utilisateur_id) values (38, 'eu', 'erat volutpat in congue etiam justo etiam', 10);
insert into congelateur (id, nom, description, utilisateur_id) values (39, 'luctus', 'vel nisl duis ac nibh fusce', 3);
insert into congelateur (id, nom, description, utilisateur_id) values (40, 'a', 'viverra pede ac diam cras pellentesque', 3);
insert into congelateur (id, nom, description, utilisateur_id) values (41, 'metus', 'pretium iaculis diam erat fermentum', 1);
insert into congelateur (id, nom, description, utilisateur_id) values (42, 'duis', 'augue vestibulum rutrum rutrum neque aenean', 4);
insert into congelateur (id, nom, description, utilisateur_id) values (43, 'ut', 'ante ipsum primis in faucibus', 14);
insert into congelateur (id, nom, description, utilisateur_id) values (44, 'cubilia', 'in purus eu magna vulputate', 14);
insert into congelateur (id, nom, description, utilisateur_id) values (45, 'nisl', 'maecenas rhoncus aliquam lacus morbi', 4);
insert into congelateur (id, nom, description, utilisateur_id) values (46, 'mauris', 'neque vestibulum eget vulputate ut ultrices vel augue', 1);
insert into congelateur (id, nom, description, utilisateur_id) values (47, 'turpis', 'in est risus auctor sed tristique', 6);
insert into congelateur (id, nom, description, utilisateur_id) values (48, 'tortor', 'massa id nisl venenatis lacinia', 10);
insert into congelateur (id, nom, description, utilisateur_id) values (49, 'aliquam', 'turpis enim blandit mi in porttitor pede justo', 3);
insert into congelateur (id, nom, description, utilisateur_id) values (50, 'cum', 'nisi venenatis tristique fusce congue', 13);
